# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProxiSante
                                 A QGIS plugin
 Un plugin pour trouver le chemin le plus court d'un point de départ (coordonnées en X/Y) vers les hôpitaux les plus proche.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-28
        git sha              : $Format:%H$
        copyright            : (C) 2024 by YC/SDS
        email                : samuel.dos-santos@etu.umontpellier.fr, ylane.crouzet@etu.umontpellier.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import *
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtWidgets import *
from qgis.core import *
from qgis.gui import *
from typing import *
from math import *
from .Temps_de_trajet_vers_hopitaux import Temps_de_trajet_vers_hopitaux

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ProxiSante_dialog import ProxiSanteDialog
import os.path

class ProxiSante:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ProxiSante_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
        
        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&ProxiSante')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ProxiSante', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ProxiSante/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Itineraires trouvant le chemin le plus rapide vers des hopitaux'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ProxiSante'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ProxiSanteDialog()
                
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()

        # See if OK was pressed
        if result:

        # Récupère le nom d'une couche
            textMapLayer1 = self.dlg.mMapLayerComboBox.currentText()
            textMapLayer2 = self.dlg.mMapLayerComboBox_2.currentText()

        # Récupérer les coordonnées départ
            Coordonnees_depart_texte = self.dlg.lineEdit.displayText().strip()
            point_depart = self.Obtenir_Coordonnees_depart(Coordonnees_depart_texte)
            if not point_depart:
                return  # Interrompre si la conversion a échoué

            layer1 = None
            layer2 = None
            for layer in QgsProject.instance().mapLayers().values():
                if layer.name() == textMapLayer1:
                    layer1 = layer
                if layer.name() == textMapLayer2:
                    layer2 = layer
            # Vérification des couches
            if not layer1 or not layer2:
                QMessageBox.warning(self.iface.mainWindow(), "Erreur", "Veuillez sélectionner les couches correctement.")
                return


            try:

            # Initialisation du modèle
                self.modele = Temps_de_trajet_vers_hopitaux()
                feedback = QgsProcessingFeedback()
                context = QgsProcessingContext()
                context.setProject(QgsProject.instance())

            # Parametres du modele
                pathCoordonnees = point_depart
                pathReseau = layer1.source()
                pathHopitaux = layer2.source()

                # Obtenir le chemin du projet
                project_path = QgsProject.instance().homePath()


                # Créer le dossier data s'il n'existe pas
                data_dir = os.path.join(project_path, 'data')
                if not os.path.exists(data_dir):
                    os.makedirs(data_dir)

                pathResult1 = os.path.join(project_path, 'data', 'Chemin_le_plus_rapide_pour_chaque_hopital_avec_le_temps_de_trajet_en_minutes.shp')
                pathResult2 = os.path.join(project_path, 'data', 'Trajet_le_plus_rapide_depuis_mon_point_de_depart.shp')

                parameters = {
                    'depart': pathCoordonnees,
                    'reseau_routier' : pathReseau,
                    'hopitaux': pathHopitaux,
                    'Chemin_le_plus_rapide_pour_chaque_hopital_avec_le_temps_de_trajet_en_minutes': pathResult1,
                    'Trajet_le_plus_rapide_depuis_mon_point_de_depart': pathResult2
                }

         # Execution de l'algorithme
                self.modele.initAlgorithm()
                results = self.modele.processAlgorithm(parameters, context, feedback)
        
        # Charger et styliser les résultats

                if results:
                    self.charger_resultats(
                        results['Chemin_le_plus_rapide_pour_chaque_hopital_avec_le_temps_de_trajet_en_minutes'],
                        results['Trajet_le_plus_rapide_depuis_mon_point_de_depart']
                    )
            except Exception as e:
                QMessageBox.warning(self.iface.mainWindow(), "Erreur", f"Une erreur s'est produite lors du traitement : {str(e)}")



    def charger_resultats(self, pathResult1, pathResult2):
        # Charger le premier résultat (tous les chemins)
        vlayer1 = QgsVectorLayer(pathResult1, "Chemins vers les hopitaux", "ogr")
        if vlayer1.isValid():
        # Créer un symbole de ligne bleue
            symbol1 = QgsLineSymbol.createSimple({
                'line_color': '0,0,255,255',  # Bleu
                'line_width': '1',
                'line_style': 'solid'
            })
            vlayer1.renderer().setSymbol(symbol1)
            vlayer1.triggerRepaint()
            QgsProject.instance().addMapLayer(vlayer1)

    # Charger le deuxième résultat (chemin le plus rapide)
        vlayer2 = QgsVectorLayer(pathResult2, "Hopital le plus proche", "ogr")
        if vlayer2.isValid():
        # Créer un symbole de ligne rouge plus épaisse
            symbol2 = QgsLineSymbol.createSimple({
                'line_color': '255,0,0,255',  # Rouge
                'line_width': '2',
                'line_style': 'solid'
            })
            vlayer2.renderer().setSymbol(symbol2)
            vlayer2.triggerRepaint()
            QgsProject.instance().addMapLayer(vlayer2)


        # Récupérer l'échelle depuis le widget
        scale = self.dlg.mScaleWidget.scale()
        
        if vlayer1.isValid() and vlayer2.isValid():
            canvas = self.iface.mapCanvas()
            
            # Définir l'étendue
            extent = vlayer1.extent()
            extent.combineExtentWith(vlayer2.extent())
            extent.scale(1.1)  # Marge de 10%
            
            # Appliquer l'échelle et l'étendue
            canvas.setExtent(extent)
            if scale > 0:
                canvas.zoomScale(scale)
            canvas.refresh()


    def Obtenir_Coordonnees_depart(self, Coordonnees_depart_texte):
        try:
                # Nettoyer et séparer les coordonnées
            Coordonnees = Coordonnees_depart_texte.strip().split(',')
            if len(Coordonnees) != 2:
                raise ValueError("Format de coordonnées invalide")
                
                # Convertir en nombres flottants
            lat, lon = map(float, Coordonnees)
            point = QgsPointXY(lat, lon)

            return point
        except (ValueError, IndexError) as e:
            QMessageBox.warning(None, "Erreur", f"Format de coordonnées invalide. Utilisez le format: latitude, longitude (ex: 43.611050,3.873164). Erreur: {str(e)}")
            return None