name: Mirror to GitHub
on:
  push:
    branches:
      - main
      - pages

jobs:
  mirror:
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror to GitHub
        run: |
          git remote add github https://${{ secrets._GITHUB_USERNAME }}:${{ secrets._GITHUB_TOKEN }}@github.com/Geomagicien34/Portfolio_SIG.git
          git push github --mirror